const fs = require('fs');

// 1. Fix OperatorPortal.jsx
let operatorContent = fs.readFileSync('src/portals/OperatorPortal.jsx', 'utf8');

// The injected block
const badInjection = `              <div style={{ marginTop: '20px', padding: '20px', backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}>
                <h3 style={{ color: '#166534', margin: 0, fontSize: '1.1rem' }}>🤖 Smart Driver Planner</h3>
                <p style={{ color: '#166534', margin: 0, fontSize: '0.85rem', textAlign: 'center', maxWidth: '600px' }}>
                  Click below to automatically generate step-by-step driver timelines for all days based on your text descriptions, hotels, and meals. You can manually edit the times above after generation.
                </p>
                <button type="button" onClick={handleAutoGenerateDriverPlanner} style={{ padding: '10px 20px', backgroundColor: '#22c55e', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Edit3 size={16} /> Auto-Generate Driver Route
                </button>
              </div>

              <button type="submit" className="btn-primary"`;

// Remove the bad injection from wherever it is and restore the original button
operatorContent = operatorContent.replace(badInjection, '<button type="submit" className="btn-primary"');

// Insert it at the correct location (before "Publish Tour & Itinerary")
const correctInjection = `              <div style={{ marginTop: '20px', padding: '20px', backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', width: '100%' }}>
                <h3 style={{ color: '#166534', margin: 0, fontSize: '1.1rem' }}>🤖 Smart Driver Planner</h3>
                <p style={{ color: '#166534', margin: 0, fontSize: '0.85rem', textAlign: 'center', maxWidth: '600px' }}>
                  Click below to automatically generate step-by-step driver timelines for all days based on your text descriptions, hotels, and meals. You can manually edit the times above after generation.
                </p>
                <button type="button" onClick={handleAutoGenerateDriverPlanner} style={{ padding: '10px 20px', backgroundColor: '#22c55e', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Edit3 size={16} /> Auto-Generate Driver Route
                </button>
              </div>

              <button type="submit" className="btn-primary" style={{ alignSelf: 
'center', width: '100%', maxWidth: '300px', padding: '14px' }}>
                Publish Tour & Itinerary`;

operatorContent = operatorContent.replace(`              <button type="submit" className="btn-primary" style={{ alignSelf: 
'center', width: '100%', maxWidth: '300px', padding: '14px' }}>
                Publish Tour & Itinerary`, correctInjection);

fs.writeFileSync('src/portals/OperatorPortal.jsx', operatorContent);


// 2. Fix DriverPortal.jsx GPS always on
let driverContent = fs.readFileSync('src/portals/DriverPortal.jsx', 'utf8');

driverContent = driverContent.replace(
  "  // HTML5 Geolocation Watcher\n  useEffect(() => {\n    if (!isSimulating || !tourData) return;\n    \n    const watchId = navigator.geolocation.watchPosition(",
  "  // HTML5 Geolocation Watcher\n  useEffect(() => {\n    if (!tourData) return;\n    \n    const watchId = navigator.geolocation.watchPosition("
);

// We can also remove the "GPS Badge" toggle in the header since it's always on now
const gpsBadgeOld = `          <div style={styles.gpsBadge}>
            <span style={{
              width: '8px', height: '8px', borderRadius: '50%',
              backgroundColor: isSimulating ? '#22c55e' : '#94a3b8',
              animation: isSimulating ? 'mapPulse 1.5s infinite' : 'none'
            }} />
            <span style={{ fontSize: '0.65rem', fontWeight: '700' }}>
              {isSimulating ? 'LIVE' : 'OFF'}
            </span>
          </div>`;

const gpsBadgeNew = `          <div style={styles.gpsBadge}>
            <span style={{
              width: '8px', height: '8px', borderRadius: '50%',
              backgroundColor: '#22c55e',
              animation: 'mapPulse 1.5s infinite'
            }} />
            <span style={{ fontSize: '0.65rem', fontWeight: '700' }}>
              GPS ACTIVE
            </span>
          </div>`;

driverContent = driverContent.replace(gpsBadgeOld, gpsBadgeNew);

fs.writeFileSync('src/portals/DriverPortal.jsx', driverContent);

console.log("Fixed OperatorPortal UI injection and DriverPortal GPS always-on");
