const fs = require('fs');
let content = fs.readFileSync('src/portals/OperatorPortal.jsx', 'utf8');

const autoGenFunction = `
  const handleAutoGenerateDriverPlanner = () => {
    const updatedDays = itineraryDays.map(day => {
      let timeOffset = 9; // starts at 9:00 AM
      const newActivities = [];
      const text = day.activities.toLowerCase();

      // 1. Hotel Pickup or Arrival
      if (text.includes('arrive') || text.includes('airport') || text.includes('flight') || (day.transport && day.transport.includes('Flight'))) {
        newActivities.push({ time: '08:30 AM', title: 'Airport Pickup / Proceed to Hotel' });
        timeOffset = 10;
      } else if (day.hotelName) {
        newActivities.push({ time: '09:00 AM', title: \`Pickup from \${day.hotelName}\` });
      } else {
        newActivities.push({ time: '09:00 AM', title: 'Start Day' });
      }

      // 2. Look for keywords in activities
      const knownSights = [
        'taj mahal', 'agra fort', 'fatehpur sikri', 'amber fort', 'hawa mahal', 'city palace', 
        'akshardham', 'qutub minar', 'india gate', 'ganges', 'rickshaw', 'boat ride'
      ];

      knownSights.forEach(sight => {
        if (text.includes(sight)) {
          const formattedTime = \`\${String(timeOffset > 12 ? timeOffset - 12 : timeOffset).padStart(2, '0')}:00 \${timeOffset >= 12 ? 'PM' : 'AM'}\`;
          newActivities.push({ time: formattedTime, title: \`Visit \${sight.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}\` });
          timeOffset += 2;
        }
      });

      if (timeOffset === 9 || timeOffset === 10) {
        newActivities.push({ time: '10:30 AM', title: 'Proceed to City Sightseeing' });
        timeOffset = 13;
      }

      // 3. Lunch
      if ((day.mealPlan && day.mealPlan.toLowerCase().includes('lunch')) || text.includes('lunch')) {
        newActivities.push({ time: '01:30 PM', title: 'Lunch Break' });
        timeOffset = 15; // 3 PM
      }

      // 4. Drop-off / Evening
      if (text.includes('dinner')) {
        newActivities.push({ time: '07:00 PM', title: 'Proceed for Dinner' });
        if (day.hotelName) {
          newActivities.push({ time: '09:00 PM', title: \`Drop back to \${day.hotelName}\` });
        }
      } else if (day.hotelName) {
        newActivities.push({ time: '05:30 PM', title: \`Drop back to \${day.hotelName}\` });
      } else {
        newActivities.push({ time: '05:30 PM', title: 'End of Day Transit' });
      }

      // Deduplicate if any exact time/title matches
      const uniqueActs = [];
      newActivities.forEach(act => {
        if (!uniqueActs.some(u => u.title === act.title && u.time === act.time)) {
          uniqueActs.push(act);
        }
      });

      return { ...day, activitiesList: uniqueActs };
    });

    setItineraryDays(updatedDays);
  };
`;

if (!content.includes('handleAutoGenerateDriverPlanner')) {
  // insert before handlePublishTour
  content = content.replace("  const handlePublishTour = async (e) => {", autoGenFunction + "\n  const handlePublishTour = async (e) => {");
}

const uiSection = `
              <div style={{ marginTop: '20px', padding: '20px', backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}>
                <h3 style={{ color: '#166534', margin: 0, fontSize: '1.1rem' }}>🤖 Smart Driver Planner</h3>
                <p style={{ color: '#166534', margin: 0, fontSize: '0.85rem', textAlign: 'center', maxWidth: '600px' }}>
                  Click below to automatically generate step-by-step driver timelines for all days based on your text descriptions, hotels, and meals. You can manually edit the times above after generation.
                </p>
                <button type="button" onClick={handleAutoGenerateDriverPlanner} style={{ padding: '10px 20px', backgroundColor: '#22c55e', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Edit3 size={16} /> Auto-Generate Driver Route
                </button>
              </div>

              <button type="submit" className="btn-primary"`;

content = content.replace('<button type="submit" className="btn-primary"', uiSection);

fs.writeFileSync('src/portals/OperatorPortal.jsx', content);
console.log('OperatorPortal.jsx updated for Driver Planner Generation');
