import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const dictionary = {
  EN: {
    // General / Shared
    langToggle: "KO",
    travelWithUs: "Travel with Us",
    koreanWelcome: "우리와 함께 여행하세요",
    loadingSplash: "Spreading colors of India...",
    viewItinerary: "VIEW ITINERARY",
    portalAccess: "PORTAL ACCESS",
    guideLogin: "Guide Login",
    driverLogin: "Driver Login",
    operatorLogin: "Operator Login",
    enterTourCode: "Enter your unique tour code below",
    accessJourney: "Access Your Journey",
    backToLogin: "Back to Login",
    tourCodePlaceholder: "e.g. JI-2026-X8J",
    callGuide: "Call Local Guide",
    navigate: "Navigate to Gate",
    openMap: "Open in Google Maps",
    liveSync: "LiveSync Active",
    cPax: "Client",
    todayItinerary: "Today's Itinerary",
    yourTeam: "Your Service Team",
    driver: "Driver",
    guide: "Guide",
    contactNo: "Mobile",
    nextUp: "NEXT UP",
    meals: "Meal Plan",
    vehicle: "Vehicle Status",
    vehicleReg: "Reg No.",
    waterStock: "Water Stock",
    adequate: "Adequate (12 btls)",
    low: "Low - Operator Notified",
    viewTicket: "View Ticket",
    activeComplaints: "Active Complaints",
    todayTours: "Today's Tours",
    filter: "Filter",
    printPdf: "Print PDF",
    onSchedule: "On Schedule",
    delayed: "Delayed",
    highPriority: "High Priority",
    reportIssue: "Report Issue",
    submit: "Submit",
    cancel: "Cancel",

    // Client Portal specific
    diningCurated: "Curated Dining Spots",
    authenticRaj: "Authentic Indian Food",
    driverEnRoute: "Driver en route",
    arrivingIn: "Arriving in 15 mins",
    clientConcierge: "Maru Concierge",
    botWelcome: "Hello! I am your Maru Concierge. How can I help you today on your journey in India?",
    botOptionItinerary: "Show my Day Plan",
    botOptionDriver: "Check Driver Status",
    botOptionCompliant: "File a Complaint",
    botOptionAmenity: "Request Special Service",
    botComplaintSelect: "What is the complaint regarding?",
    complaintDriver: "Driver Service",
    complaintGuide: "Guide Service",
    complaintHotel: "Hotel Service",
    complaintVehicle: "Vehicle & AC",
    complaintOther: "Other Request",
    complaintSuccess: "Your complaint has been submitted. Our company manager (reshu.ranjan@gmail.com) has been notified instantly.",
    botServiceSelect: "What special service do you require?",
    serviceWater: "Extra Mineral Water",
    serviceWheelchair: "Wheelchair Assistance",
    serviceMeal: "Vegetarian Meal Request",
    serviceAmenity: "Extra Room Amenities",
    serviceSuccess: "Your request is registered! We've sent a priority alert to the operator and emailed reshu.ranjan@gmail.com.",
    botItineraryAns: "Today's sightseeing is: ",
    botDriverAns: "Your Chauffeur is {name}. Vehicle No: {car}. The GPS tracker shows they are active!",

    // Operator Portal specific
    operatorDashboard: "Daily Movement",
    createTour: "Create New Tour",
    tourName: "Tour Name",
    clientName: "Client Name(s)",
    tourCode: "Tour Code",
    dateRange: "Date Range",
    selectDates: "Select dates",
    globalResources: "Global Resources",
    addNewGuide: "Add New Guide",
    addNewDriver: "Add New Driver",
    guideName: "Guide Name",
    driverName: "Driver Name",
    driverMobile: "Driver Mobile",
    vehicleNo: "Vehicle Number",
    vehicleType: "Vehicle Type",
    itineraryBuilder: "Itinerary Builder",
    addDay: "Add Day",
    day: "Day",
    city: "City",
    selectCity: "Select City",
    addCustomCity: "+ Add New City",
    hotelName: "Hotel Name",
    hotelAddress: "Hotel Address",
    mapsLink: "Google Maps Link",
    mealPlan: "Meal Plan",
    transportMedium: "Transport Medium",
    bySurface: "By Surface (Car/SUV)",
    byTrain: "By Train",
    byFlight: "By Flight",
    flightNo: "Flight Number",
    activities: "Activities / Notes",
    publishTour: "Publish Tour",
    swapGuide: "Swap Guide",
    swapDriver: "Swap Driver",
    newGuidePlaceholder: "Guide Full Name",
    newDriverPlaceholder: "Driver Full Name",

    // Driver Portal specific
    driverPortalTitle: "Driver Dispatch Portal",
    simulateLocation: "Simulate GPS Movement",
    locationLive: "Broadcasting Location Live",
    locationIdle: "GPS Idle",
    nextDestination: "Next Destination Target",
    currentStatus: "Current Task",
    driverReportTitle: "Report Delay / Vehicle Mechanical Issue",
    driverProblemLabel: "Select Issue:",
    driverTraffic: "Heavy Traffic Delay",
    driverFlatTire: "Flat Tire / Mechanical Delay",
    driverACissue: "Vehicle AC Not Cooling",
    driverIllness: "Driver / Guest Assistance Needed",
    driverReportSuccess: "Alert sent to Operator & Manager immediately!",

    // Guide Portal specific
    guidePortalTitle: "Local Expert Companion Portal",
    guideItineraryOverview: "Guest Itinerary Overview",

    // New additions for Management Panel / Overhaul
    mgmtDashboard: 'Dashboard',
    mgmtCities: 'Cities',
    mgmtActivities: 'Activities',
    mgmtHotels: 'Hotels',
    mgmtGuides: 'Guides',
    mgmtDrivers: 'Drivers',
    mgmtTourBuilder: 'Tour Builder',
    addCity: 'Add New City',
    addActivity: 'Add New Activity',
    addHotel: 'Add New Hotel',
    cityName: 'City Name',
    cityTagline: 'City Tagline',
    cityDescription: 'Description',
    bestTime: 'Best Time to Visit',
    languages: 'Languages Spoken',
    currencyLabel: 'Currency',
    transportOptions: 'Transport Options',
    emergencyNumbers: 'Emergency Numbers',
    foodSpecialties: 'Food Specialties',
    travelTips: 'Travel Tips',
    starRating: 'Star Rating',
    receptionPhone: 'Reception Phone',
    amenitiesLabel: 'Amenities',
    vehicleTypes: 'Vehicle Type',
    carNumber: 'Car Number',
    mobileNumber: 'Mobile Number',
    activityTitle: 'Activity Title',
    activityDesc: 'Activity Description',
    estimatedTime: 'Estimated Time',
    imageUrl: 'Image URL',
    googleMapsUrl: 'Google Maps URL',
    searchPlaceholder: 'Search...',
    noResults: 'No results found',
    confirmDelete: 'Are you sure you want to delete?',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    totalCities: 'Total Cities',
    totalHotels: 'Total Hotels',
    totalActivities: 'Total Activities',
    totalGuides: 'Total Guides',
    totalDrivers: 'Total Drivers',
    activeTours: 'Active Tours',
    dailyMovement: 'Daily Movement',
    selectDate: 'Select Date',
    noActiveTours: 'No active tours for this date',
    tourDetails: 'Tour Details',
    changeGuide: 'Change Guide',
    changeDriver: 'Change Driver',
    guideStatus: 'Guide Status',
    busyStatus: 'BUSY',
    availableStatus: 'AVAILABLE',
    busyUntil: 'Busy until',
    markArrived: 'Mark as Arrived',
    arrived: 'Arrived ✓',
    nextStop: 'Next Stop',
    currentLocation: 'Current Location',
    driverItinerary: 'Your Itinerary',
    dayByDay: 'Day by Day Schedule',
    pax: 'Passengers',
    checkInOut: 'Check In/Out',
    pool: 'Pool',
    spa: 'Spa',
    restaurant: 'Restaurant',
    gym: 'Gym',
    wifi: 'WiFi',
    barLounge: 'Bar/Lounge',
    roomService: 'Room Service',
    laundry: 'Laundry',
    parking: 'Parking',
    airportShuttle: 'Airport Shuttle',
    amPm: 'AM/PM',
    startTime: 'Start Time',
    endTime: 'End Time',
    selectHotel: 'Select Hotel',
    selectActivity: 'Select Activity',
    selectGuide: 'Select Guide',
    selectDriver: 'Select Driver',
    tourNotStartedYet: 'Tour not started yet',
    tourCompleted: 'Tour completed',
    firstDayOfTour: 'First day of tour is',
    lastDayOfTour: 'Last day of tour was',
    noActivitiesToday: 'No activities scheduled for today (Leisure Day)',
    changeTourCode: 'Change Tour Code',
    loadTour: 'Load Tour',
    activeGuide: 'Active Guide',
    pickupLocation: 'Pickup / Meeting Point',
    activityStatus: 'Activity Status',
    statusScheduled: 'Scheduled',
    statusEnRoute: 'Boarding / En Route',
    statusCompleted: 'Completed',
    broadcastMsg: 'Broadcast Announcement',
    dailyTasks: 'Daily Guide Tasks',
    sendAlert: 'Send Announcement',
    currentDate: 'Selected Date',
    nextDestinationTarget: 'Target Destination'
  },
  KO: {
    // General / Shared
    langToggle: "EN",
    travelWithUs: "우리와 함께 여행하세요",
    koreanWelcome: "우리와 함께 여행하세요",
    loadingSplash: "인도의 색채가 펼쳐집니다...",
    viewItinerary: "일정 확인하기",
    portalAccess: "포털 접속",
    guideLogin: "가이드 로그인",
    driverLogin: "드라이버 로그인",
    operatorLogin: "관리자 로그인",
    enterTourCode: "배정받으신 투어 코드를 입력해주세요",
    accessJourney: "당신의 여정에 접속하세요",
    backToLogin: "로그인으로 돌아가기",
    tourCodePlaceholder: "예: JI-2026-X8J",
    callGuide: "가이드에게 전화하기",
    navigate: "입구 길찾기",
    openMap: "구글 지도에서 열기",
    liveSync: "실시간 동기화 중",
    cPax: "고객명",
    todayItinerary: "오늘의 투어 일정",
    yourTeam: "서비스 전담 팀",
    driver: "드라이버",
    guide: "현지 가이드",
    contactNo: "연락처",
    nextUp: "다음 일정",
    meals: "식사 계획",
    vehicle: "차량 상태",
    vehicleReg: "차량 번호",
    waterStock: "생수 보유량",
    adequate: "충분함 (12병 잔여)",
    low: "부족함 - 본사 알림 완료",
    viewTicket: "티켓 보기",
    activeComplaints: "접수된 민원 현황",
    todayTours: "오늘 진행 중인 투어",
    filter: "필터링",
    printPdf: "PDF 일정표 출력",
    onSchedule: "정상 진행",
    delayed: "지연됨",
    highPriority: "긴급 처리",
    reportIssue: "문제 보고하기",
    submit: "제출하기",
    cancel: "취소",

    // Client Portal specific
    diningCurated: "엄선된 추천 맛집",
    authenticRaj: "정통 인도 현지식",
    driverEnRoute: "드라이버 이동 중",
    arrivingIn: "15분 내 도착 예정",
    clientConcierge: "마루 컨시어지",
    botWelcome: "안녕하세요! 마루 컨시어지 챗봇입니다. 오늘 즐거운 인도 여행을 위해 무엇을 도와드릴까요?",
    botOptionItinerary: "오늘 전체 일정 보기",
    botOptionDriver: "기사님 실시간 정보",
    botOptionCompliant: "불만/민원 신고하기",
    botOptionAmenity: "특별 서비스 요청",
    botComplaintSelect: "어떤 부분에 불편함이 있으신가요?",
    complaintDriver: "가이드 서비스 만족도",
    complaintGuide: "기사님 서비스 만족도",
    complaintHotel: "호텔 객실 및 서비스",
    complaintVehicle: "차량 및 에어컨 결함",
    complaintOther: "기타 긴급 건의사항",
    complaintSuccess: "불만 사항이 성공적으로 제출되었습니다. 본사 총괄 관리자(reshu.ranjan@gmail.com)에게 즉시 통보되었습니다.",
    botServiceSelect: "어떤 특별 서비스가 필요하십니까?",
    serviceWater: "추가 미네랄 생수 제공",
    serviceWheelchair: "휠체어 이동 지원",
    serviceMeal: "채식(베지테리언) 식사 변경",
    serviceAmenity: "호텔 객실 어메니티 추가",
    serviceSuccess: "요청이 접수되었습니다! 담당 오퍼레이터에게 긴급 알림이 전송되었으며 reshu.ranjan@gmail.com으로 메일이 전송되었습니다.",
    botItineraryAns: "오늘의 주요 관광 일정은 다음과 같습니다: ",
    botDriverAns: "전담 드라이버는 {name} 님이며, 차량 번호는 {car} 입니다. 현재 GPS 트래커가 작동 중입니다!",

    // Operator Portal specific
    operatorDashboard: "당일 운행 관리 현황",
    createTour: "신규 투어 등록",
    tourName: "투어 명칭",
    clientName: "고객명 (패밀리/인원)",
    tourCode: "투어 코드",
    dateRange: "여행 일정 기간",
    selectDates: "날짜 선택",
    globalResources: "마스터 데이터 리소스",
    addNewGuide: "신규 가이드 추가",
    addNewDriver: "신규 드라이버 추가",
    guideName: "가이드 성함",
    driverName: "드라이버 성함",
    driverMobile: "기사 연락처",
    vehicleNo: "차량 등록 번호",
    vehicleType: "차량 차종",
    itineraryBuilder: "일별 세부 일정 빌더",
    addDay: "일정 추가",
    day: "일차",
    city: "방문 도시",
    selectCity: "도시 선택",
    addCustomCity: "+ 새 도시 추가",
    hotelName: "투숙 호텔명",
    hotelAddress: "호텔 상세 주소",
    mapsLink: "구글 지도 경로 링크",
    mealPlan: "제공 식사 정보",
    transportMedium: "이동 수단",
    bySurface: "전용 차량 육로 이동",
    byTrain: "열차 이동",
    byFlight: "국내선 항공 이동",
    flightNo: "항공편 번호",
    activities: "관광 상세 코스 / 비고사항",
    publishTour: "투어 일정 발행",
    swapGuide: "가이드 즉시 변경",
    swapDriver: "드라이버 즉시 변경",
    newGuidePlaceholder: "가이드 성함 입력",
    newDriverPlaceholder: "드라이버 성함 입력",

    // Driver Portal specific
    driverPortalTitle: "배정 드라이버 운행 포털",
    simulateLocation: "GPS 실시간 위치 전송 시뮬레이터",
    locationLive: "실시간 위치 정보 공유 중",
    locationIdle: "GPS 대기 상태",
    nextDestination: "다음 목적지 주소",
    currentStatus: "현재 수행 임무",
    driverReportTitle: "운행 지연 및 차량 고장/민원 즉시 보고",
    driverProblemLabel: "발생 현황 선택:",
    driverTraffic: "극심한 도로 정체 지연",
    driverFlatTire: "차량 펑크 및 기계 결함 지연",
    driverACissue: "차량 에어컨 냉방 작동 불량",
    driverIllness: "운전자 지원 요청 / 고객 특이사항",
    driverReportSuccess: "관리자 및 대표 이메일로 긴급 경보가 즉시 전송되었습니다!",

    // Guide Portal specific
    guidePortalTitle: "배정 가이드 전담 포털",
    guideItineraryOverview: "고객별 전체 세부 일정표",

    // New additions translated
    mgmtDashboard: '대시보드',
    mgmtCities: '도시 관리',
    mgmtActivities: '활동 관리',
    mgmtHotels: '호텔 관리',
    mgmtGuides: '가이드 관리',
    mgmtDrivers: '드라이버 관리',
    mgmtTourBuilder: '투어 빌더',
    addCity: '새 도시 추가',
    addActivity: '새 활동 추가',
    addHotel: '새 호텔 추가',
    cityName: '도시 이름',
    cityTagline: '도시 슬로건',
    cityDescription: '설명',
    bestTime: '최적 방문 시기',
    languages: '사용 언어',
    currencyLabel: '통화',
    transportOptions: '교통 수단',
    emergencyNumbers: '긴급 연락처',
    foodSpecialties: '음식 특산물',
    travelTips: '여행 팁',
    starRating: '호텔 등급',
    receptionPhone: '프론트 전화',
    amenitiesLabel: '시설/편의시설',
    vehicleTypes: '차량 유형',
    carNumber: '차량 번호',
    mobileNumber: '휴대폰 번호',
    activityTitle: '활동 제목',
    activityDesc: '활동 설명',
    estimatedTime: '예상 소요시간',
    imageUrl: '이미지 URL',
    googleMapsUrl: '구글 지도 URL',
    searchPlaceholder: '검색...',
    noResults: '검색 결과가 없습니다',
    confirmDelete: '정말 삭제하시겠습니까?',
    save: '저장',
    edit: '수정',
    delete: '삭제',
    close: '닫기',
    totalCities: '전체 도시',
    totalHotels: '전체 호텔',
    totalActivities: '전체 활동',
    totalGuides: '전체 가이드',
    totalDrivers: '전체 드라이버',
    activeTours: '진행 중인 투어',
    dailyMovement: '일일 운행 현황',
    selectDate: '날짜 선택',
    noActiveTours: '해당 날짜에 활성 투어가 없습니다',
    tourDetails: '투어 상세',
    changeGuide: '가이드 변경',
    changeDriver: '드라이버 변경',
    guideStatus: '가이드 상태',
    busyStatus: '배정중',
    availableStatus: '가능',
    busyUntil: '배정 종료일',
    markArrived: '도착 완료',
    arrived: '도착 ✓',
    nextStop: '다음 목적지',
    currentLocation: '현재 위치',
    driverItinerary: '배정 일정',
    dayByDay: '일별 상세 일정',
    pax: '인원',
    checkInOut: '체크인/아웃',
    pool: '수영장',
    spa: '스파',
    restaurant: '레스토랑',
    gym: '헬스장',
    wifi: '와이파이',
    barLounge: '바/라운지',
    roomService: '룸서비스',
    laundry: '세탁',
    parking: '주차',
    airportShuttle: '공항 셔틀',
    amPm: '오전/오후',
    startTime: '시작 시간',
    endTime: '종료 시간',
    selectHotel: '호텔 선택',
    selectActivity: '활동 선택',
    selectGuide: '가이드 선택',
    selectDriver: '드라이버 선택',
    tourNotStartedYet: '투어가 아직 시작되지 않았습니다',
    tourCompleted: '투어가 종료되었습니다',
    firstDayOfTour: '투어 첫째 날은',
    lastDayOfTour: '투어 마지막 날은',
    noActivitiesToday: '오늘 일정이 없습니다 (자유 일정)',
    changeTourCode: '투어 코드 변경',
    loadTour: '투어 로드',
    activeGuide: '담당 가이드',
    pickupLocation: '탑승 / 미팅 위치',
    activityStatus: '진행 상태',
    statusScheduled: '대기 중',
    statusEnRoute: '이동/탑승 중',
    statusCompleted: '완료',
    broadcastMsg: '안내 방송',
    dailyTasks: '일일 가이드 업무',
    sendAlert: '방송 전송',
    currentDate: '선택된 날짜',
    nextDestinationTarget: '목적지 대상'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('KO'); // Default is Korean as requested

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'EN' ? 'KO' : 'EN'));
  };

  const t = (key) => {
    return dictionary[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
